apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.fastapi.port }}
    targetPort: {{ .Values.fastapi.port }}
    protocol: TCP
  selector:
    {{- include "wiki-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      {{- include "wiki-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wiki-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "wiki-chart.fullname" . }}-fastapi-sa
      initContainers:
      - name: wait-for-postgres
        # use postgres client image to get pg_isready utility
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        securityContext:
          runAsNonRoot: false
        command:
        - sh
        - -c
        - |
          until pg_isready -h {{ include "wiki-chart.fullname" . }}-postgres -p 5432 -U {{ .Values.postgresql.auth.username }}; do
            echo "Waiting for Postgres to be ready..."
            sleep 2
          done
      containers:
      - name: fastapi
        image: "{{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}"
        imagePullPolicy: {{ .Values.fastapi.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.fastapi.port }}
        env:
        - name: DB_USER
          value: {{ .Values.postgresql.auth.username }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wiki-chart.fullname" . }}-postgres-secret
              key: password
        - name: DB_HOST
          value: {{ include "wiki-chart.fullname" . }}-postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: {{ .Values.postgresql.auth.database }}
        resources:
          requests:
            cpu: {{ .Values.fastapi.resources.requests.cpu }}
            memory: {{ .Values.fastapi.resources.requests.memory }}
          limits:
            cpu: {{ .Values.fastapi.resources.limits.cpu }}
            memory: {{ .Values.fastapi.resources.limits.memory }}
        securityContext:
          runAsUser: {{ .Values.fastapi.runAsUser }}
          runAsGroup: {{ .Values.fastapi.runAsGroup }}
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.fastapi.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.fastapi.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
      securityContext:
        runAsNonRoot: {{ .Values.fastapi.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.fastapi.runAsUser }}
        runAsGroup: {{ .Values.fastapi.runAsGroup }}
        fsGroup: {{ .Values.fastapi.fsGroup }}
