apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana-dashboards
  namespace: {{ .Values.namespace }}
data:
  creation-dashboard.json: |
    {
      "dashboard": {
        "title": "creation",
        "uid": "creation-dashboard-678",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Users & Posts Creation Rate",
            "type": "graph",
            "gridPos": {
              "h": 12,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "targets": [
              {
                "expr": "rate(users_created_total[5m])",
                "refId": "A",
                "legendFormat": "Users/sec"
              },
              {
                "expr": "rate(posts_created_total[5m])",
                "refId": "B",
                "legendFormat": "Posts/sec"
              }
            ],
            "yaxes": [
              {
                "format": "short",
                "label": "Rate (per sec)"
              },
              {
                "format": "short",
                "label": ""
              }
            ]
          },
          {
            "id": 2,
            "title": "Total Users Created",
            "type": "stat",
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 0,
              "y": 12
            },
            "targets": [
              {
                "expr": "users_created_total",
                "refId": "A"
              }
            ]
          },
          {
            "id": 3,
            "title": "Total Posts Created",
            "type": "stat",
            "gridPos": {
              "h": 4,
              "w": 6,
              "x": 6,
              "y": 12
            },
            "targets": [
              {
                "expr": "posts_created_total",
                "refId": "A"
              }
            ]
          }
        ],
        "refresh": "10s",
        "schemaVersion": 26,
        "version": 0
      },
      "overwrite": true
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana-datasources
  namespace: {{ .Values.namespace }}
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "wiki-chart.fullname" . }}-prometheus:9090
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana-provisioning
  namespace: {{ .Values.namespace }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'Dashboard Provider'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana-secret
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: {{ include "wiki-chart.fullname" . }}-grafana
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.grafana.runAsUser | default 472 }}
        fsGroup: {{ .Values.grafana.fsGroup | default 472 }}
      containers:
      - name: grafana
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.adminUser }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wiki-chart.fullname" . }}-grafana-secret
              key: admin-password
        - name: GF_SERVER_ROOT_URL
          value: http://localhost/grafana/
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        resources:
          requests:
            cpu: {{ .Values.grafana.resources.requests.cpu }}
            memory: {{ .Values.grafana.resources.requests.memory }}
          limits:
            cpu: {{ .Values.grafana.resources.limits.cpu }}
            memory: {{ .Values.grafana.resources.limits.memory }}
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboard-files
          mountPath: /var/lib/grafana/dashboards
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.grafana.runAsUser | default 472 }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: {{ include "wiki-chart.fullname" . }}-grafana-pvc
      - name: grafana-datasources
        configMap:
          name: {{ include "wiki-chart.fullname" . }}-grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: {{ include "wiki-chart.fullname" . }}-grafana-provisioning
      - name: dashboard-files
        configMap:
          name: {{ include "wiki-chart.fullname" . }}-grafana-dashboards
