apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana-secret
type: Opaque
stringData:
  admin-password: {{ include "wiki-chart.getOrGeneratePassword" (dict "value" .Values.grafana.adminPassword "key" "admin-password" "name" (printf "%s-grafana-secret" (include "wiki-chart.fullname" .)) "namespace" .Values.namespace "context" .) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana
  namespace: {{ .Values.namespace }}
