# Default-deny policy for the namespace. This is a best practice.
# It blocks all ingress traffic unless another policy explicitly allows it.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiki-chart.fullname" . }}-default-deny-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
# Specific policy for FastAPI
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "wiki-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from Prometheus for scraping metrics
    - from:
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: {{ .Values.fastapi.port }}
    # Allow from Ingress Controller (Traefik in k3d)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: {{ .Values.fastapi.port }}
    # Allow from the test job
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: test
      ports:
        - protocol: TCP
          port: {{ .Values.fastapi.port }}
    # Allow from Postgres (for TCP handshake during initContainer checks)
    - from:
      - podSelector:
          matchLabels:
            app: postgres
  egress:
    # Allow to Postgres
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432
    # Allow DNS requests for any external communication
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
---
# Allow traffic to Postgres from the FastAPI app
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiki-chart.fullname" . }}-allow-to-postgres
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "wiki-chart.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: 5432