apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fastapi
