apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiki-chart.fullname" . }}-postgres-config
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wiki-chart.fullname" . }}-postgres
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: {{ include "wiki-chart.fullname" . }}-postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: {{ include "wiki-chart.fullname" . }}-postgres-sa
      initContainers:
      - name: set-data-permission
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          chown -R {{ .Values.postgresql.securityContext.runAsUser | default 999 }}:{{ .Values.postgresql.securityContext.runAsGroup | default 999 }} /var/lib/postgresql/data
        securityContext:
          runAsUser: 0 # Run as root to have permission to chown
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      securityContext:
        runAsUser: {{ .Values.postgresql.securityContext.runAsUser | default 999 }}
        runAsGroup: {{ .Values.postgresql.securityContext.runAsGroup | default 999 }}
        fsGroup: {{ .Values.postgresql.securityContext.fsGroup | default 999 }}
      containers:
      - name: postgres
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: {{ include "wiki-chart.fullname" . }}-postgres-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wiki-chart.fullname" . }}-postgres-secret
              key: password
        resources:
          requests:
            cpu: {{ .Values.postgresql.resources.requests.cpu }}
            memory: {{ .Values.postgresql.resources.requests.memory }}
          limits:
            cpu: {{ .Values.postgresql.resources.limits.cpu }}
            memory: {{ .Values.postgresql.resources.limits.memory }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        securityContext:
          runAsNonRoot: {{ .Values.postgresql.securityContext.runAsNonRoot | default true }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U {{ .Values.postgresql.auth.username }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U {{ .Values.postgresql.auth.username }}
          initialDelaySeconds: 5
          periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresql.primary.persistence.size }}
        {{- if .Values.postgresql.primary.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.primary.persistence.storageClass }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None # This makes the service "headless", which is required for a StatefulSet
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
