# test-policy.yaml
# This policy grants the helm test pod the necessary egress permissions
# to connect to the services it needs to test.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiki-chart.fullname" . }}-test-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {{ .Values.test.selectorLabels | toYaml | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    # Allow to FastAPI
    - to:
        - podSelector:
            matchLabels: {{ .Values.fastapi.selectorLabels | toYaml | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.fastapi.port }}
    # Allow to Grafana
    - to:
        - podSelector:
            matchLabels: {{ .Values.grafana.selectorLabels | toYaml | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.grafana.port }}
    # Allow to Prometheus
    - to:
        - podSelector:
            matchLabels: {{ .Values.prometheus.selectorLabels | toYaml | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.prometheus.port }}
    # Allow DNS requests for service discovery
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53