apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wiki-chart.fullname" . }}-test
  annotations:
    "helm.sh/hook": test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "wiki-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: test
    spec:
      serviceAccountName: {{ include "wiki-chart.fullname" . }}-test
      restartPolicy: Never
      containers:
      - name: test
        image: curlimages/curl:8.1.0
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "=== Wiki Chart Integration Tests ==="
          echo ""
          
          # Wait for FastAPI service to be ready
          echo "Waiting for FastAPI service to be ready..."
          i=1
          while [ $i -le 30 ]; do
            if curl -s -f http://{{ include "wiki-chart.fullname" . }}-fastapi:8000/ > /dev/null 2>&1; then
              echo "✓ FastAPI service is ready"
              break
            fi
            echo "Attempt $i/30: Waiting..."
            sleep 2
            i=$((i+1))
          done
          
          if [ $i -gt 30 ]; then
            echo "✗ Timeout waiting for FastAPI service."
            exit 1
          fi

          BASE_URL="http://{{ include "wiki-chart.fullname" . }}-fastapi:8000"
          
          # Test 1: Root endpoint
          echo ""
          echo "Test 1: GET / (root endpoint)"
          if curl -s "$BASE_URL/" | grep -q "User and Post API"; then
            echo "✓ Root endpoint works"
          else
            echo "✗ Root endpoint failed"
            exit 1
          fi
          
          # Test 2: Create user
          echo ""
          echo "Test 2: POST /users (create user)"
          USER_RESPONSE=$(curl -s -X POST "$BASE_URL/users" \
            -H "Content-Type: application/json" \
            -d '{"name": "TestUser"}')
          if echo "$USER_RESPONSE" | grep -q '"id"'; then
            echo "✓ Create user works"
          else
            echo "✗ Create user failed"
            exit 1
          fi
          
          # Test 3: Get user
          echo ""
          echo "Test 3: GET /user/1 (get user by ID)"
          if curl -s "$BASE_URL/user/1" | grep -q '"name":"TestUser"'; then
            echo "✓ Get user works"
          else
            echo "✗ Get user failed"
            exit 1
          fi
          
          # Test 4: Create post
          echo ""
          echo "Test 4: POST /posts (create post)"
          POST_RESPONSE=$(curl -s -X POST "$BASE_URL/posts" \
            -H "Content-Type: application/json" \
            -d '{"user_id": 1, "content": "Test post"}')
          if echo "$POST_RESPONSE" | grep -q '"post_id"'; then
            echo "✓ Create post works"
          else
            echo "✗ Create post failed"
            exit 1
          fi
          
          # Test 5: Get post
          echo ""
          echo "Test 5: GET /posts/1 (get post by ID)"
          if curl -s "$BASE_URL/posts/1" | grep -q '"content":"Test post"'; then
            echo "✓ Get post works"
          else
            echo "✗ Get post failed"
            exit 1
          fi
          
          # Test 6: Metrics endpoint
          echo ""
          echo "Test 6: GET /metrics (Prometheus metrics)"
          if curl -s "$BASE_URL/metrics" | grep -q "users_created_total"; then
            echo "✓ Metrics endpoint works"
          else
            echo "✗ Metrics endpoint failed"
            exit 1
          fi
          
          # Test 7: Grafana health endpoint
          echo ""
          echo "Test 7: GET /api/health (Grafana health)"
          GRAFANA_URL="http://{{ include "wiki-chart.fullname" . }}-grafana:3000"
          if curl -s "$GRAFANA_URL/api/health" | grep -q '"database":"ok"'; then
            echo "✓ Grafana health endpoint works"
          else
            echo "✗ Grafana health endpoint failed"
            exit 1
          fi

          # Test 8: Prometheus health endpoint
          echo ""
          echo "Test 8: GET /-/healthy (Prometheus health)"
          PROMETHEUS_URL="http://{{ include "wiki-chart.fullname" . }}-prometheus:9090"
          if curl -s "$PROMETHEUS_URL/-/healthy" | grep -q "Prometheus is Healthy."; then
            echo "✓ Prometheus health endpoint works"
          else
            echo "✗ Prometheus health endpoint failed"
            exit 1
          fi

          echo ""
          echo "=== All tests passed ==="
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiki-chart.fullname" . }}-test
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: test
